name: "Weather Forecast Action"
description: "Display weather forcast for any area in a project README"
author: "woodrock"

inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true
  OPEN_WEATHER_TOKEN:
    description: "Open Weather API Token"
    required: true
  CITY:
    description: "City to get forecast for"
    required: true

runs:
  using: "node12"
  main: "dist/index.js"
